"""Phép thử A/B: bộ chấm có phân biệt nổi ẢNH CHỤP THẬT với ẢNH MÁY VẼ không?

    python scripts/judge_ab_test.py --config configs/vast_arms.yaml --ids S001,S002,S003 \
        --runs /workspace/runs/pilotC [--set llm.backend=mistral_vl]

Đây là phép kiểm rẻ nhất và **không cần nhãn người**. Lấy từ FAGER (arXiv 2605.19111): ghép một ảnh thật với
một ảnh sinh rồi hỏi bộ chấm cái nào là ảnh chụp thật của vật đó. Nếu nó không phân biệt nổi thì mọi con số
khác của nó đều vô nghĩa, và không có công thức chấm điểm nào cứu được.

Mốc trong bài FAGER, trên phần Culture: FAGER 0,97 · FineGRAIN 0,83 · **VQAScore 0,47** (đúng bằng tung đồng
xu). Nên 0,5 KHÔNG phải sàn an toàn, nó là kết quả thật của một thước đo đang được dùng rộng rãi.

Hai điều để con số không bị thổi phồng:
  - Hỏi CẢ HAI THỨ TỰ (thật trước / sinh trước) rồi lấy trung bình, vì model có thiên lệch vị trí.
  - Ảnh thật dùng ở đây lấy từ `candidates/`, KHÁC bộ `selected/` mà IP-Adapter đã dùng để sinh ảnh; nếu
    không thì đang hỏi "ảnh nào giống ảnh điều kiện hơn" chứ không phải "ảnh nào thật hơn".
"""

from __future__ import annotations

import argparse
import glob
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from ctig.config import Config, set_dotted  # noqa: E402
from ctig.pipeline import load_prompts  # noqa: E402
from ctig.session import Session  # noqa: E402

Q = ("One of these two images is a real photograph of {entity}. The other was generated by an image model.\n"
     "A. the first image is the real photograph\n"
     "B. the second image is the real photograph\n"
     "Answer with a single letter, A or B.")


def gen_images(runs: list[str], pid: str) -> list[str]:
    out: list[str] = []
    for run in runs:
        lf = Path(run) / pid / "loop_v2.json"
        if lf.exists():
            out += [x for x in (json.loads(lf.read_text()).get("kept") or []) if Path(x).exists()]
        out += [p for p in sorted(glob.glob(f"{run}/{pid}/*/*.png")) if Path(p).name != "grid.png"]
    seen, uniq = set(), []
    for p in out:
        if p not in seen:
            seen.add(p); uniq.append(p)
    return uniq


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--ids", required=True)
    ap.add_argument("--runs", required=True, help="thư mục run chứa ảnh sinh, cách nhau bằng dấu phẩy")
    ap.add_argument("--max-pairs", type=int, default=6, help="số cặp mỗi prompt")
    ap.add_argument("--out", default=None)
    ap.add_argument("--set", action="append", default=[])
    a = ap.parse_args(argv)

    ov: dict = {}
    for kv in a.set:
        k, _, v = kv.partition("=")
        set_dotted(ov, k, v)
    cfg = Config.load(a.config, ov)
    prompts = {p.id: p for p in load_prompts(cfg.prompts_path)}
    runs = [x.strip() for x in a.runs.split(",") if x.strip()]
    log = lambda *x: print(*x, flush=True)  # noqa: E731

    rows, agent = [], None
    for pid in [x.strip() for x in a.ids.split(",") if x.strip()]:
        if pid not in prompts:
            log(f"[{pid}] không có trong bộ prompt"); continue
        s = Session(cfg, prompts[pid], run_dir=Path(cfg.runs_dir) / "abtest", log=lambda *x: None)
        agent = s.agent
        # ảnh thật phải KHÁC bộ đã dùng làm điều kiện IP-Adapter
        used = set(s.prompt_refs(include_candidates=False))
        reals = [r for r in s.prompt_refs(include_candidates=True) if r not in used]
        gens = gen_images(runs, pid)
        if not reals or not gens:
            log(f"[{pid}] thiếu ảnh: {len(reals)} thật (ngoài bộ điều kiện), {len(gens)} sinh"); continue
        entity = prompts[pid].text_en or pid
        q = Q.format(entity=entity)
        n = 0
        for g in gens:
            if n >= a.max_pairs:
                break
            r = reals[n % len(reals)]
            # hỏi hai thứ tự để khử thiên lệch vị trí
            p1 = agent.vqa_choice2(q, [r, g], 2) if hasattr(agent, "vqa_choice2") else None
            p1 = p1 or _choice(agent, q, [r, g])
            p2 = _choice(agent, q, [g, r])
            if p1 is None or p2 is None:
                log(f"[{pid}] backend không hỗ trợ choice_prob nhiều ảnh -> dừng"); return
            p_real = (p1[0] + p2[1]) / 2.0          # A khi thật đứng trước, B khi thật đứng sau
            rows.append({"prompt_id": pid, "real": r, "gen": g, "p_real": round(p_real, 3),
                         "p_order1": round(p1[0], 3), "p_order2": round(p2[1], 3)})
            log(f"  {pid} {Path(g).parent.name:18s} P(nhận ra ảnh thật) = {p_real:.2f} "
                f"(thứ tự 1: {p1[0]:.2f} · thứ tự 2: {p2[1]:.2f})")
            n += 1

    if not rows:
        raise SystemExit("không tạo được cặp nào")
    acc = sum(r["p_real"] > 0.5 for r in rows) / len(rows)
    mean = sum(r["p_real"] for r in rows) / len(rows)
    # chênh giữa hai thứ tự = mức thiên lệch vị trí; lớn thì con số trung bình cũng đáng ngờ
    bias = sum(abs(r["p_order1"] - r["p_order2"]) for r in rows) / len(rows)
    print(f"\n{len(rows)} cặp (ảnh thật vs ảnh sinh)")
    print(f"  ĐỘ CHÍNH XÁC: {acc:.2f}   (FAGER 0,97 · FineGRAIN 0,83 · VQAScore 0,47 · tung đồng xu 0,50)")
    print(f"  P(nhận ra ảnh thật) trung bình: {mean:.2f}")
    print(f"  thiên lệch vị trí trung bình: {bias:.2f}" + ("  ← lớn, con số trên kém tin" if bias > 0.3 else ""))
    if acc <= 0.6:
        print("\n  Bộ chấm KHÔNG phân biệt nổi ảnh chụp với ảnh máy vẽ. Mọi điểm văn hoá nó cho đều đáng ngờ,")
        print("  và không công thức chấm điểm nào cứu được — phải đổi cách hỏi hoặc đổi thước đo.")
    if a.out:
        Path(a.out).write_text(json.dumps(rows, ensure_ascii=False, indent=1), encoding="utf-8")
        print(f"  chi tiết -> {a.out}")


def _choice(agent, q: str, images: list[str]):
    fn = getattr(getattr(agent, "llm", None), "choice_prob", None)
    if fn is None:
        return None
    try:
        return [float(x) for x in fn(q, images, ("A", "B"))]
    except Exception:  # noqa: BLE001
        return None


if __name__ == "__main__":
    main()
